server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /exercises       { proxy_pass http://api:8000; }
    location /templates       { proxy_pass http://api:8000; }
    location /workouts        { proxy_pass http://api:8000; }
    location /progress        { proxy_pass http://api:8000; }
    location /auth            { proxy_pass http://api:8000; }
    location /nutrition       { proxy_pass http://api:8000; }
    location /custom-workouts { proxy_pass http://api:8000; }
    location /docs            { proxy_pass http://api:8000; }
    location /openapi.json    { proxy_pass http://api:8000; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}