# Signed-Out UX Review

Per file I have two sections the bugs section and what works well section. 
Majority of these feature work well but there are some small bugs or stuff that shouldnt be there.



############ Bugs

#### Front Page
- [ ] Success story carousel does not go to the last dot/slide. Easy fix
- [ ] Get Started Today button does not perform its intended action. Easy fix

#### Nutrition
- [ ] N/A

#### History
- [ ] N/A

#### Workout Templates
- [ ] exercise bar in custom workout is useless
- [ ] allows a custom template with no exercise
- [ ] does not save custom workouts
- [ ] not a bug but terrible UI for both pages. Overall just need a touch up
- [ ] can not begin saved customized workout templates


#### Active Workout
- [ ] Does its purpose but in terms of design needs Total rework. This is the most alarming feature we have.

#### Exercise Library
- [ ] N/A could use more instructions but thats for exercise api


#### Navbar
- [ ] N/A

#### Footer
- [ ] N/A

#### Login
- [ ] Not really a bug but a home button is required

#### Sign Up
- [ ] Not really a bug but a home button is required








#
#
#
#################################################################
########### What Works Well

#### Front Page
- [ ] works as intended

#### Nutrition
- [ ]. Doesnt let you log foods which makes sense 

#### History
- [ ]. works well doesnt track exercises until signed in. same with foods

#### Workout Templates
- [ ] Can pick a workout

#### Active Workout
- [ ]. Can simulate a workout

#### Exercise Library
- [ ] works as it should

#### Account/Profile
- [ ] N/A when signed out.

#### Navbar
- [ ]  works well no bugs

#### Footer
- [ ] works well no bugs

#### Login
- [ ] works well no bugs, 

#### Sign Up
- [ ] works well no bugs
