# Signed-In UX Review


Per file I have two sections the bugs section and what works well section. 
Majority of these feature work well but there are some small bugs or stuff that shouldnt be there.


############# Bugs

#### Front Page
- [ ] Success story carousel does not go to the last dot/slide. Easy fix
- [ ] Get Started Today button does not perform its intended action. Easy fix

#### Nutrition
- [ ]  N/A

#### History
- [ ]  performace trends is doesnt really work. Cant track exercises unless I did it wrong

#### Workout Templates
- [ ] exercise bar in custom workout is useless
- [ ] allows a custom template with no exercise
- [ ] does not save custom workouts
- [ ] not a bug but terrible UI for both pages. Need a touch up
- [ ] Did not save exercise template done in history even if signed in


#### Active Workout
- [ ] Does its purpose but in terms of design needs Total rework. Most alarming feature we have.
  

#### Exercise Library
- [ ] N/A could use more description but thats for other api

#### Account/Profile
- [ ] a lot of those buttons dont do anything ex: gmail, workout sounds

#### Navbar
- [ ] N/A

#### Footer
- [ ] N/A

 




#
#
############################################
######### What Works Well

#### Front Page
- [ ] Front page buttons route correctly.

#### Nutrition
- [ ] Works really well!

#### History
- [ ] Calorie tracker works well

#### Workout Templates
- [ ] Can pick a workout

#### Active Workout
- [ ] Can simulate a workout

#### Exercise Library
- [ ] works as it should

#### Account/Profile
- [ ] can look at profile and edit certain features

#### Navbar
- [ ] NavBar works well no bugs

#### Footer
- [ ] Footer works well No bugs



